services:
  db: 
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    depends_on:
      - db
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  api:
    build: ./api
    command: python manage.py runserver
    ports:
      - 8001:8001
    depends_on:
      - db 
      - mqtt

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
    

volumes:
  db_data:
  